### ISSUE TITLE
please add parameter to specify collection

### ISSUE THREAD

**Issue by brainbuz** [miku/solrbulk#1]
solrbulk can only be used to import to the default collection.

**Comment by miku** [comment]
Good point, thanks. PR welcome otherwise I take care of it in about ten day when I'm back from my trip.

**Comment by miku** [comment]
I added an optional `-collection` flag. It's included in the latest release: https://github.com/miku/solrbulk/releases/tag/v0.1.5.4

If you don't have any objections, I would close this issue in a few days.
